UPDATE City
SET Id = newId();

ALTER TABLE [City] ALTER COLUMN [Id] UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE [City] ALTER COLUMN [Name] NVARCHAR(255) NOT NULL;

ALTER TABLE City
ADD CONSTRAINT PK_City PRIMARY KEY (Id);