CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FullName] NVARCHAR(100) NOT NULL,
	[Username] NVARCHAR(20) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[PhoneNumber] NVARCHAR (20) NULL,
	[Email] NVARCHAR (100) NULL,
	[SocialMediaLink] NVARCHAR (MAX) NULL,
	[City]  UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_City] FOREIGN KEY ([City]) REFERENCES [City]([Id])
)






